# Generated by Django 5.1.2 on 2024-10-25 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charactersheets', '0002_item_skill_spell_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='charactersheet',
            name='heroic_inspiration',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='charactersheet',
            name='walking_speed',
            field=models.IntegerField(default=30),
        ),
    ]
