# Generated by Django 5.1.2 on 2024-10-25 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charactersheets', '0003_charactersheet_heroic_inspiration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='charactersheet',
            name='max_health',
            field=models.IntegerField(default=30),
        ),
    ]
